service:
  name: service-otel-collector
image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest
containerPort: 4317
resources:
  limits:
    memory: "200Mi"
  requests:
    memory: "64Mi"
    cpu: "100m"
env: []
nodeSelector:
  eks.amazonaws.com/nodegroup: graviton-workers
